/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import static main.java.Main.setUserSessionID;

/**
 *
 * @author admin
 */
public class MainLogIn extends javax.swing.JFrame {

    private static final String EMAIL_PATTERN
            = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@(cvsu\\.edu\\.ph|cvsu-silang\\.edu\\.ph)$";

    public static boolean isValidEmail(String email) {
        Pattern pattern = Pattern.compile(EMAIL_PATTERN);
        Matcher matcher = pattern.matcher(email);
        return matcher.matches();
    }

    public void autoCompleteEmail(JTextField field) {
        if (!field.getText().trim().equals(PLACEHOLDER_EMAIL) && !field.getText().trim().contains("@")) {
            fieldEmail.setText(field.getText().trim() + "@cvsu.edu.ph");
        }
    }

    private final String PLACEHOLDER_EMAIL = "Enter Email Address";
    private final String PLACEHOLDER_PASSWORD = "**************";

    /**
     * Creates new form Main
     */
    public MainLogIn() {
        initComponents();
        
        Utils.setTransparentFrame(fieldEmail, fieldPassword, btnForgotPasword);
        Utils.resetBtnIcon(btnForgotPasword);
        
        fieldEmail.getDocument().addDocumentListener(new FieldChangeListener());
        fieldPassword.getDocument().addDocumentListener(new FieldChangeListener());
    }

    private class FieldChangeListener implements DocumentListener, ActionListener {

        @Override
        public void insertUpdate(DocumentEvent e) {
            checkFields();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            checkFields();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            checkFields();
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            checkFields();
        }

        private void checkFields() {
            String user_email = fieldEmail.getText().trim();
            String user_password = new String(fieldPassword.getPassword()).trim();

            btnLogIn.setEnabled(!user_email.isEmpty()
                    && !user_email.equals(PLACEHOLDER_EMAIL)
                    && !user_password.isEmpty()
                    && !user_password.equals(PLACEHOLDER_PASSWORD));
        }
    }

    private void logInAccount() {
        byte[] user_salt = null;
        String user_email = fieldEmail.getText();

        String saltQuery = "SELECT user_salt FROM " + Main.TB_USER + " WHERE user_email = ?";
        try (Connection conn = Utils.getConnection(Main.DB_NAME); PreparedStatement pst = conn.prepareStatement(saltQuery)) {
            pst.setString(1, user_email);
            try (ResultSet rs = pst.executeQuery()) {
                if (rs.next()) {
                    user_salt = Utils.stringToByte(rs.getString("user_salt"));
                } else {
                    JOptionPane.showMessageDialog(this, "This email does not exist!", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        } catch (SQLException e) {
            Utils.paneDatabaseError(e);
            return;
        }

        String user_password = Utils.toHash(new String(fieldPassword.getPassword()).trim(), user_salt);
        String query = "SELECT * FROM " + Main.TB_USER + " WHERE user_email = ? AND user_password = ?";

        try (Connection conn = Utils.getConnection(Main.DB_NAME); PreparedStatement pst = Utils.prepareQueryWithParameters(conn, query, user_email, user_password); ResultSet rs = pst.executeQuery()) {
            if (rs.next()) {
                int userID = rs.getInt("employee_ID");
                setUserSessionID(userID);

                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Wrong Email or Password!", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            Utils.paneDatabaseError(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        labelHeader = new javax.swing.JLabel();
        imageLogo = new javax.swing.JLabel();
        panelLogIn = new javax.swing.JPanel();
        btnLogIn = new javax.swing.JButton();
        btnForgotPasword = new javax.swing.JButton();
        imageSilang = new javax.swing.JLabel();
        labelInventorySystem = new javax.swing.JLabel();
        panelLogInFields = new javax.swing.JPanel();
        fieldEmail = new javax.swing.JTextField();
        fieldPassword = new javax.swing.JPasswordField();
        labelEmail = new javax.swing.JLabel();
        imageEmailBg = new javax.swing.JLabel();
        imagePasswordBg = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        imageHeader = new javax.swing.JLabel();
        labelBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cavite State Univeristy Inventory System");
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        getContentPane().setLayout(null);

        panelHeader.setBackground(new java.awt.Color(25, 102, 24));

        labelHeader.setFont(new java.awt.Font("Bebas", 0, 24)); // NOI18N
        labelHeader.setForeground(new java.awt.Color(255, 255, 255));
        labelHeader.setText("Cavite State University Inventory System");

        imageLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/cvsu-logo.png"))); // NOI18N
        imageLogo.setToolTipText(null);

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(labelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 691, Short.MAX_VALUE)
                .addComponent(imageLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
            .addComponent(labelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(panelHeader);
        panelHeader.setBounds(0, 0, 1370, 70);

        panelLogIn.setBackground(new java.awt.Color(246, 243, 237));
        panelLogIn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(25, 102, 24)));
        panelLogIn.setMaximumSize(new java.awt.Dimension(427, 500));
        panelLogIn.setMinimumSize(new java.awt.Dimension(427, 500));

        btnLogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/interface/btnLogIn.png"))); // NOI18N
        btnLogIn.setBorder(null);
        btnLogIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogIn.setEnabled(false);
        btnLogIn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/interface/btnLogIn_pressed.png"))); // NOI18N
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });

        btnForgotPasword.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        btnForgotPasword.setForeground(new java.awt.Color(255, 102, 102));
        btnForgotPasword.setText("FORGOT PASSWORD?");
        btnForgotPasword.setBorder(null);
        btnForgotPasword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnForgotPasword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForgotPaswordActionPerformed(evt);
            }
        });

        imageSilang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageSilang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/cvsu-silang-logo.png"))); // NOI18N

        labelInventorySystem.setBackground(new java.awt.Color(25, 102, 24));
        labelInventorySystem.setFont(new java.awt.Font("Bebas", 0, 48)); // NOI18N
        labelInventorySystem.setForeground(new java.awt.Color(255, 255, 255));
        labelInventorySystem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelInventorySystem.setText("inventory system");
        labelInventorySystem.setOpaque(true);

        panelLogInFields.setOpaque(false);
        panelLogInFields.setLayout(null);

        fieldEmail.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        fieldEmail.setForeground(new java.awt.Color(153, 153, 153));
        fieldEmail.setText("Enter Email Address");
        fieldEmail.setBorder(null);
        fieldEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldEmailFocusLost(evt);
            }
        });
        panelLogInFields.add(fieldEmail);
        fieldEmail.setBounds(10, 50, 360, 20);

        fieldPassword.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        fieldPassword.setForeground(new java.awt.Color(153, 153, 153));
        fieldPassword.setText("**************");
        fieldPassword.setBorder(null);
        fieldPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldPasswordFocusLost(evt);
            }
        });
        panelLogInFields.add(fieldPassword);
        fieldPassword.setBounds(10, 130, 360, 30);

        labelEmail.setFont(new java.awt.Font("Aaux ProThin OSF", 1, 18)); // NOI18N
        labelEmail.setText("Email Address");
        panelLogInFields.add(labelEmail);
        labelEmail.setBounds(0, 6, 173, 22);

        imageEmailBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/interface/fieldLogIn.png"))); // NOI18N
        panelLogInFields.add(imageEmailBg);
        imageEmailBg.setBounds(0, 40, 377, 37);

        imagePasswordBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/interface/fieldLogIn.png"))); // NOI18N
        panelLogInFields.add(imagePasswordBg);
        imagePasswordBg.setBounds(0, 123, 377, 40);

        labelPassword.setFont(new java.awt.Font("Aaux ProThin OSF", 1, 18)); // NOI18N
        labelPassword.setText("Password");
        panelLogInFields.add(labelPassword);
        labelPassword.setBounds(0, 89, 105, 22);

        javax.swing.GroupLayout panelLogInLayout = new javax.swing.GroupLayout(panelLogIn);
        panelLogIn.setLayout(panelLogInLayout);
        panelLogInLayout.setHorizontalGroup(
            panelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageSilang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelInventorySystem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelLogInLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLogInLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btnLogIn))
                    .addComponent(panelLogInFields, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLogInLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnForgotPasword)
                .addGap(145, 145, 145))
        );
        panelLogInLayout.setVerticalGroup(
            panelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogInLayout.createSequentialGroup()
                .addComponent(imageSilang, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelInventorySystem, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelLogInFields, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnLogIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnForgotPasword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        getContentPane().add(panelLogIn);
        panelLogIn.setBounds(480, 140, 420, 500);

        imageHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/bg_header.png"))); // NOI18N
        getContentPane().add(imageHeader);
        imageHeader.setBounds(0, -33, 1366, 160);

        labelBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/bg.png"))); // NOI18N
        labelBg.setToolTipText(null);
        getContentPane().add(labelBg);
        labelBg.setBounds(0, 10, 1366, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        String user_email = fieldPassword.getText();
        if (isValidEmail(user_email)) {
            logInAccount();
        } else {
            Utils.paneInvalidEmail();
        }
    }//GEN-LAST:event_btnLogInActionPerformed

    private void btnForgotPaswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForgotPaswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnForgotPaswordActionPerformed

    private void fieldEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldEmailFocusGained
        Utils.setDefaultField(fieldEmail, PLACEHOLDER_EMAIL, Utils.FieldFocus.GAINED, Color.BLACK);
    }//GEN-LAST:event_fieldEmailFocusGained

    private void fieldEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldEmailFocusLost
        Utils.setDefaultField(fieldEmail, PLACEHOLDER_EMAIL, Utils.FieldFocus.LOST, Color.BLACK);
        autoCompleteEmail(fieldEmail);
    }//GEN-LAST:event_fieldEmailFocusLost

    private void fieldPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldPasswordFocusGained
        Utils.setDefaultField(fieldPassword, PLACEHOLDER_PASSWORD, Utils.FieldFocus.GAINED, Color.BLACK);
    }//GEN-LAST:event_fieldPasswordFocusGained

    private void fieldPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldPasswordFocusLost
        Utils.setDefaultField(fieldPassword, PLACEHOLDER_PASSWORD, Utils.FieldFocus.LOST, Color.BLACK);
    }//GEN-LAST:event_fieldPasswordFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainLogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnForgotPasword;
    private javax.swing.JButton btnLogIn;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JLabel imageEmailBg;
    private javax.swing.JLabel imageHeader;
    private javax.swing.JLabel imageLogo;
    private javax.swing.JLabel imagePasswordBg;
    private javax.swing.JLabel imageSilang;
    private javax.swing.JLabel labelBg;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelHeader;
    private javax.swing.JLabel labelInventorySystem;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelLogIn;
    private javax.swing.JPanel panelLogInFields;
    // End of variables declaration//GEN-END:variables
}
