/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ProjectINSY.java.ui.component;

import ProjectINSY.java.swing.shadow.ShadowRenderer;
import static ProjectINSY.java.util.GuiUtil.setTransparentFrame;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.awt.image.BufferedImage;
import javax.swing.JFrame;

/**
 *
 * @author admin
 */
public class Header extends javax.swing.JPanel {

    /**
     * Creates new form Header
     */
    public Header() {
        initComponents();

        setTransparentFrame(btnMenu);
//        btnMenu.setEnabled(false);
        btnMenu.setToolTipText("This action requires logging in!");
        btnMenu.setMnemonic(KeyEvent.VK_ESCAPE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMenu = new javax.swing.JButton();
        labelHeader = new javax.swing.JLabel();
        imageLogo = new javax.swing.JLabel();
        blur = new ProjectINSY.java.ui.panel.GradientPanel();

        setOpaque(false);
        setLayout(null);

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectINSY/resources/interface/btnMenu.png"))); // NOI18N
        btnMenu.setBorder(null);
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectINSY/resources/interface/btnMenu_active.png"))); // NOI18N
        btnMenu.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectINSY/resources/interface/btnMenu_active.png"))); // NOI18N
        add(btnMenu);
        btnMenu.setBounds(20, 20, 49, 30);

        labelHeader.setFont(new java.awt.Font("Bebas", 0, 30)); // NOI18N
        labelHeader.setForeground(new java.awt.Color(255, 255, 255));
        labelHeader.setText("CAVITE STATE UNIVERSITY INVENTORY SYSTEM");
        add(labelHeader);
        labelHeader.setBounds(80, 10, 600, 50);

        imageLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectINSY/resources/images/cvsu-logo.png"))); // NOI18N
        add(imageLogo);
        imageLogo.setBounds(1280, 0, 70, 70);

        blur.setColorEnd(new java.awt.Color(25, 102, 24));
        blur.setColorStart(new java.awt.Color(25, 102, 24));
        blur.setShadowIntensity(255);

        javax.swing.GroupLayout blurLayout = new javax.swing.GroupLayout(blur);
        blur.setLayout(blurLayout);
        blurLayout.setHorizontalGroup(
            blurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1420, Short.MAX_VALUE)
        );
        blurLayout.setVerticalGroup(
            blurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        add(blur);
        blur.setBounds(-20, -20, 1420, 100);
    }// </editor-fold>//GEN-END:initComponents

    private int x;
    private int y;

    public void initMoving(JFrame fram) {
        this.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent me) {
                x = me.getX();
                y = me.getY();
            }

        });
        this.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent me) {
                fram.setLocation(me.getXOnScreen() - x, me.getYOnScreen() - y);
            }
        });
    }

    public void addEventMenu(ActionListener event) {
        btnMenu.addActionListener(event);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ProjectINSY.java.ui.panel.GradientPanel blur;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel imageLogo;
    private javax.swing.JLabel labelHeader;
    // End of variables declaration//GEN-END:variables
}
