package ProjectINSY.java.ui.panel;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.beans.PropertyChangeSupport;

/**
 *
 * @author Dric
 */
public class GradientPanel extends ProjectINSY.java.ui.panel.ShadowPanel {

    private Color colorStart = Color.decode("#FFFFFF");
    private Color colorEnd = Color.decode("#D6D9DF");

    private final PropertyChangeSupport pcs = new PropertyChangeSupport(this);

    /**
     * Creates new form GradientPanel
     */
    public GradientPanel() {
        initComponents();
        setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        Graphics2D graphics = (Graphics2D) g;
        graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        GradientPaint gradient = new GradientPaint(0, 0, colorStart, 0, getHeight(), colorEnd);
        graphics.setPaint(gradient);
        graphics.fillRoundRect(getShadowSize(), getShadowSize(), getWidth() - 2 * getShadowSize(), getHeight() - 2 * getShadowSize(), 15, 15);
    }

    public Color getColorStart() {
        return colorStart;
    }

    public void setColorStart(Color colorStart) {
        Color oldColorStart = this.colorStart;
        this.colorStart = colorStart;
        pcs.firePropertyChange("colorStart", oldColorStart, colorStart);
        repaint();  // Repaint the panel to reflect the color change
    }

    public Color getColorEnd() {
        return colorEnd;
    }

    public void setColorEnd(Color colorEnd) {
        Color oldColorEnd = this.colorEnd;
        this.colorEnd = colorEnd;
        pcs.firePropertyChange("colorEnd", oldColorEnd, colorEnd);
        repaint();  // Repaint the panel to reflect the color change
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
