/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ProjectINSY.java.ui;

import static ProjectINSY.java.util.GuiUtil.setForm;
import static ProjectINSY.java.util.GuiUtil.setTransparentFrame;
import javax.swing.JComponent;

/**
 *
 * @author admin
 */
public class ItemTracker extends javax.swing.JPanel {
    
    public final ItemTrackerOut ItemTrackerOut = new ItemTrackerOut();
    public final ItemTrackerScan ItemTrackerScan = new ItemTrackerScan();

    /**
     * Creates new form LogIn
     */
    public ItemTracker() {
        initComponents();
        
        setTransparentFrame(ItemTracker.this, panelBody);
        setTransparentFrame(btnFormScan, btnFormOut);
        
        switchTrackerForm(ItemTrackerScan);
        panelPage.setVisible(false);
    }
    
    public void switchTrackerForm(JComponent com) {
        setForm(panelBody, com);
        
        if (com == ItemTrackerOut) {
            btnFormScan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectINSY/resources/interface/btnTracker_active.png")));
            btnFormOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectINSY/resources/interface/btnTracker.png")));
            
            ItemTrackerOut.repopulateFilterComboBox();
        } else {
            btnFormScan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectINSY/resources/interface/btnTracker.png")));
            btnFormOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectINSY/resources/interface/btnTracker_active.png")));
            
            ItemTrackerScan.repopulateSuggestions();
            ItemTrackerScan.setScannerFocus();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPage = new javax.swing.JPanel();
        labelFormOut = new javax.swing.JLabel();
        btnFormOut = new javax.swing.JButton();
        labelFormScan = new javax.swing.JLabel();
        btnFormScan = new javax.swing.JButton();
        panelMain = new javax.swing.JPanel();
        panelBody = new javax.swing.JPanel();

        panelPage.setBackground(new java.awt.Color(255, 255, 255));
        panelPage.setLayout(null);

        labelFormOut.setFont(new java.awt.Font("Bebas", 0, 24)); // NOI18N
        labelFormOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFormOut.setText("SCAN ITEM");
        labelFormOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelPage.add(labelFormOut);
        labelFormOut.setBounds(920, 6, 910, 30);

        btnFormOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectINSY/resources/interface/btnTracker.png"))); // NOI18N
        btnFormOut.setBorder(null);
        btnFormOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFormOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormOutActionPerformed(evt);
            }
        });
        panelPage.add(btnFormOut);
        btnFormOut.setBounds(920, 0, 909, 40);

        labelFormScan.setFont(new java.awt.Font("Bebas", 0, 24)); // NOI18N
        labelFormScan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFormScan.setText("ITEM LOCATION");
        labelFormScan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelPage.add(labelFormScan);
        labelFormScan.setBounds(10, 6, 900, 30);

        btnFormScan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectINSY/resources/interface/btnTracker.png"))); // NOI18N
        btnFormScan.setToolTipText("");
        btnFormScan.setBorder(null);
        btnFormScan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFormScan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormScanActionPerformed(evt);
            }
        });
        panelPage.add(btnFormScan);
        btnFormScan.setBounds(0, 0, 920, 40);

        setMaximumSize(new java.awt.Dimension(1840, 900));
        setMinimumSize(new java.awt.Dimension(1840, 900));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1840, 900));

        panelMain.setBackground(new java.awt.Color(255, 255, 255));
        panelMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(25, 102, 24), 2));

        panelBody.setBackground(new java.awt.Color(255, 255, 255));
        panelBody.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBody, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFormScanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormScanActionPerformed
        switchTrackerForm(ItemTrackerScan);
    }//GEN-LAST:event_btnFormScanActionPerformed

    private void btnFormOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormOutActionPerformed
        switchTrackerForm(ItemTrackerOut);
    }//GEN-LAST:event_btnFormOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFormOut;
    private javax.swing.JButton btnFormScan;
    private javax.swing.JLabel labelFormOut;
    private javax.swing.JLabel labelFormScan;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelPage;
    // End of variables declaration//GEN-END:variables
}
