/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ProjectINSY.java.ui;

import ProjectINSY.java.Main;
import static ProjectINSY.java.util.GuiUtil.setScrollBarCustom;
import ProjectINSY.java.util.TableUtil;
import static ProjectINSY.java.util.TableUtil.defaultTable;

/**
 *
 * @author admin
 */
public class ItemTrackerLocation extends javax.swing.JPanel {

    public String currentSearchQuery = "SELECT * FROM " + Main.TB_ITEM_STOCK + " ORDER BY stock_id ASC";

    /**
     * Creates new form ItemTrackerLocation
     */
    public ItemTrackerLocation() {
        initComponents();
        
        setScrollBarCustom(tableScroll);
        
        defaultTable(tableLocation);
        tableLocation.getColumnModel().getColumn(0).setPreferredWidth(10);
    }

    public void refreshTableInventory() {
        TableUtil.refreshTable(tableLocation, currentSearchQuery, TableUtil.TableEnum.STOCK_LOCATION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableScroll = new javax.swing.JScrollPane();
        tableLocation = new ProjectINSY.java.swing.Table();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1836, 850));

        tableScroll.setBorder(null);

        tableLocation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "", "Name", "Description", "Location", "Holder"
            }
        ));
        tableLocation.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        tableLocation.setGridColor(new java.awt.Color(255, 255, 255));
        tableLocation.setSelectionBackground(new java.awt.Color(25, 102, 24));
        tableScroll.setViewportView(tableLocation);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 1840, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 116, Short.MAX_VALUE)
                .addComponent(tableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ProjectINSY.java.swing.Table tableLocation;
    private javax.swing.JScrollPane tableScroll;
    // End of variables declaration//GEN-END:variables
}
