/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ProjectINSY.java.ui;

import ProjectINSY.java.Main;
import ProjectINSY.java.model.ItemPanel;
import ProjectINSY.java.util.GuiUtil;
import static ProjectINSY.java.util.GuiUtil.enforceDigits;
import static ProjectINSY.java.util.GuiUtil.setDefaultField;
import static ProjectINSY.java.util.GuiUtil.setScrollBarCustom;
import ProjectINSY.java.util.TableUtil;
import static ProjectINSY.java.util.GuiUtil.fieldHasValue;
import static ProjectINSY.java.util.GuiUtil.getComboSelected;
import static ProjectINSY.java.util.GuiUtil.getFieldString;
import java.awt.Color;

/**
 *
 * @author admin
 */
public class ItemStock extends ItemPanel {

    /**
     * Creates new form LogIn
     */
    public ItemStock() {
        initComponents();

        setScrollBarCustom(tableScroll);

        tableInventory.setDefaultTable();
        tableInventory.setIntegerColumn(2);
        tableInventory.setFixedColumn();
    }

    //<editor-fold defaultstate="collapsed" desc="Item Panel">
    @Override
    public void refreshItemTable() {
        filterWHERE = " ";
        if (!searchCategory.isDefaultComboItem()) {
            filterWHERE += "AND stock_category = '" + getComboSelected(searchCategory) + "' ";
        }
        if (!searchName.isDefaultComboItem()) {
            filterWHERE += "AND stock_name = '" + getComboSelected(searchName) + "' ";
        }
        if (radioCurrent.isSelected()) {
            filterWHERE += "AND stock_location = 'Supply Room' ";
        }

        filterHAVING = " ";
        if (fieldHasValue(searchQuantityStart)) {
            filterHAVING += "AND stock_quantity >= '" + getFieldString(searchQuantityStart) + "' ";
        }
        if (fieldHasValue(searchQuantityEnd)) {
            filterHAVING += "AND stock_quantity <= '" + getFieldString(searchQuantityEnd) + "' ";
        }

        currentSearchQuery = "SELECT stock_category, stock_name, COUNT(stock_name) AS stock_quantity FROM "
                + Main.TB_ITEM_STOCK
                + " LEFT JOIN "
                + Main.TB_ITEM_REPORT
                + " ON "
                + Main.TB_ITEM_STOCK + ".stock_code = " + Main.TB_ITEM_REPORT + ".report_code"
                + " WHERE " + Main.TB_ITEM_REPORT + ".report_code IS NULL "
                + filterWHERE
                + "GROUP BY stock_category, stock_name HAVING 1 "
                + filterHAVING;

        TableUtil.refreshTable(tableInventory, currentSearchQuery, TableUtil.TableEnum.STOCK_DISTINCT);
    }

    @Override
    public void repopulateFilterComboBox() {
        disableUpdatingComboBoxes();
        searchCategory.repopulateComboBox("SELECT stock_category FROM " + Main.TB_ITEM_STOCK);
        searchName.repopulateComboBox("SELECT stock_name FROM " + Main.TB_ITEM_STOCK);
        enableUpdatingComboBoxes();

        refreshItemTable();
    }

    @Override
    public void repopulateComboBox() {
    }
    //</editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        tableScroll = new javax.swing.JScrollPane();
        tableInventory = new ProjectINSY.java.swing.Table();
        panelSearch = new javax.swing.JPanel();
        searchCategory = new ProjectINSY.java.swing.ComboBoxSuggestion();
        labelFilterCategory = new javax.swing.JLabel();
        searchName = new ProjectINSY.java.swing.ComboBoxSuggestion();
        labelFilterName = new javax.swing.JLabel();
        labelFilterQuantity = new javax.swing.JLabel();
        searchQuantityStart = new ProjectINSY.java.swing.Form.FormFieldSuggestion();
        searchQuantityEnd = new ProjectINSY.java.swing.Form.FormFieldSuggestion();
        labelFilterQuantityFrom = new javax.swing.JLabel();
        labelFilterQuantityTo = new javax.swing.JLabel();
        radioCurrent = new ProjectINSY.java.swing.RadioButtonCustom();

        setMaximumSize(new java.awt.Dimension(1840, 900));
        setMinimumSize(new java.awt.Dimension(1840, 900));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1840, 900));

        panelMain.setBackground(new java.awt.Color(255, 255, 255));
        panelMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(25, 102, 24), 2));
        panelMain.setMaximumSize(new java.awt.Dimension(1840, 900));
        panelMain.setMinimumSize(new java.awt.Dimension(1840, 900));
        panelMain.setPreferredSize(new java.awt.Dimension(1840, 900));

        tableScroll.setBorder(null);

        tableInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Category", "Name", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableInventory.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        tableInventory.setGridColor(new java.awt.Color(255, 255, 255));
        tableInventory.setSelectionBackground(new java.awt.Color(25, 102, 24));
        tableScroll.setViewportView(tableInventory);

        panelSearch.setBackground(new java.awt.Color(255, 255, 255));
        panelSearch.setMaximumSize(new java.awt.Dimension(1277, 71));
        panelSearch.setMinimumSize(new java.awt.Dimension(1277, 71));

        searchCategory.setBorder(null);
        searchCategory.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        searchCategory.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                searchCategoryItemStateChanged(evt);
            }
        });

        labelFilterCategory.setFont(new java.awt.Font("Aaux ProThin OSF", 1, 24)); // NOI18N
        labelFilterCategory.setText("Category");

        searchName.setBorder(null);
        searchName.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        searchName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                searchNameItemStateChanged(evt);
            }
        });

        labelFilterName.setFont(new java.awt.Font("Aaux ProThin OSF", 1, 24)); // NOI18N
        labelFilterName.setText("Name");

        labelFilterQuantity.setFont(new java.awt.Font("Aaux ProThin OSF", 1, 24)); // NOI18N
        labelFilterQuantity.setText("Quantity Range");

        searchQuantityStart.setBorder(null);
        searchQuantityStart.setForeground(new java.awt.Color(153, 153, 153));
        searchQuantityStart.setText("1");
        searchQuantityStart.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        searchQuantityStart.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchQuantityStartFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchQuantityStartFocusLost(evt);
            }
        });
        searchQuantityStart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchQuantityStartKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchQuantityStartKeyTyped(evt);
            }
        });

        searchQuantityEnd.setBorder(null);
        searchQuantityEnd.setForeground(new java.awt.Color(153, 153, 153));
        searchQuantityEnd.setText("999999999");
        searchQuantityEnd.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        searchQuantityEnd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchQuantityEndFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchQuantityEndFocusLost(evt);
            }
        });
        searchQuantityEnd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchQuantityEndKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchQuantityEndKeyTyped(evt);
            }
        });

        labelFilterQuantityFrom.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        labelFilterQuantityFrom.setText("From");

        labelFilterQuantityTo.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        labelFilterQuantityTo.setText("To");

        radioCurrent.setBackground(new java.awt.Color(25, 102, 24));
        radioCurrent.setSelected(true);
        radioCurrent.setText("Current Stock");
        radioCurrent.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        radioCurrent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCurrentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSearchLayout = new javax.swing.GroupLayout(panelSearch);
        panelSearch.setLayout(panelSearchLayout);
        panelSearchLayout.setHorizontalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(labelFilterCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(202, 202, 202)
                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelFilterName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchName, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(208, 208, 208)
                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelSearchLayout.createSequentialGroup()
                        .addComponent(labelFilterQuantityFrom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchQuantityStart, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelFilterQuantityTo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchQuantityEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelFilterQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(radioCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelSearchLayout.setVerticalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSearchLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(searchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelFilterName)
                    .addGroup(panelSearchLayout.createSequentialGroup()
                        .addComponent(labelFilterCategory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(radioCurrent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelSearchLayout.createSequentialGroup()
                            .addComponent(labelFilterQuantity)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(searchQuantityStart, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelFilterQuantityTo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(searchQuantityEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(labelFilterQuantityFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableScroll)
                    .addComponent(panelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchQuantityEndKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchQuantityEndKeyTyped
        enforceDigits(evt);
    }//GEN-LAST:event_searchQuantityEndKeyTyped

    private void searchQuantityEndKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchQuantityEndKeyReleased
        refreshItemTable();
    }//GEN-LAST:event_searchQuantityEndKeyReleased

    private void searchQuantityEndFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchQuantityEndFocusLost
        setDefaultField(searchQuantityEnd, Main.filterMaxNumber, GuiUtil.FieldFocus.LOST, Color.BLACK);
    }//GEN-LAST:event_searchQuantityEndFocusLost

    private void searchQuantityEndFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchQuantityEndFocusGained
        setDefaultField(searchQuantityEnd, Main.filterMaxNumber, GuiUtil.FieldFocus.GAINED, Color.BLACK);
    }//GEN-LAST:event_searchQuantityEndFocusGained

    private void searchQuantityStartKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchQuantityStartKeyTyped
        enforceDigits(evt);
    }//GEN-LAST:event_searchQuantityStartKeyTyped

    private void searchQuantityStartKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchQuantityStartKeyReleased
        refreshItemTable();
    }//GEN-LAST:event_searchQuantityStartKeyReleased

    private void searchQuantityStartFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchQuantityStartFocusLost
        setDefaultField(searchQuantityStart, Main.filterMinNumber, GuiUtil.FieldFocus.LOST, Color.BLACK);
    }//GEN-LAST:event_searchQuantityStartFocusLost

    private void searchQuantityStartFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchQuantityStartFocusGained
        setDefaultField(searchQuantityStart, Main.filterMinNumber, GuiUtil.FieldFocus.GAINED, Color.BLACK);
    }//GEN-LAST:event_searchQuantityStartFocusGained

    private void searchCategoryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_searchCategoryItemStateChanged
        if (isUpdatingComboBoxes) {
            return;
        }

        disableUpdatingComboBoxes();
        searchName.repopulateAssociatedComboBox(searchCategory, "stock_category", "stock_name", "SELECT stock_name FROM " + Main.TB_ITEM_STOCK);
        enableUpdatingComboBoxes();

        refreshItemTable();
    }//GEN-LAST:event_searchCategoryItemStateChanged

    private void searchNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_searchNameItemStateChanged
        if (isUpdatingComboBoxes) {
            return;
        }

        refreshItemTable();
    }//GEN-LAST:event_searchNameItemStateChanged

    private void radioCurrentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCurrentActionPerformed
        refreshItemTable();
    }//GEN-LAST:event_radioCurrentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelFilterCategory;
    private javax.swing.JLabel labelFilterName;
    private javax.swing.JLabel labelFilterQuantity;
    private javax.swing.JLabel labelFilterQuantityFrom;
    private javax.swing.JLabel labelFilterQuantityTo;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelSearch;
    private ProjectINSY.java.swing.RadioButtonCustom radioCurrent;
    private ProjectINSY.java.swing.ComboBoxSuggestion searchCategory;
    private static ProjectINSY.java.swing.ComboBoxSuggestion searchName;
    private ProjectINSY.java.swing.Form.FormFieldSuggestion searchQuantityEnd;
    private ProjectINSY.java.swing.Form.FormFieldSuggestion searchQuantityStart;
    private ProjectINSY.java.swing.Table tableInventory;
    private javax.swing.JScrollPane tableScroll;
    // End of variables declaration//GEN-END:variables
}
