/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ProjectINSY.java.ui;

import static ProjectINSY.java.util.GuiUtil.setForm;
import static ProjectINSY.java.util.GuiUtil.setTransparentFrame;
import javax.swing.JComponent;

/**
 *
 * @author admin
 */
public class ItemTracker extends javax.swing.JPanel {
    
    public final ItemTrackerLocation ItemTrackerLocation = new ItemTrackerLocation();
    public final ItemTrackerScan ItemTrackerScan = new ItemTrackerScan();

    /**
     * Creates new form LogIn
     */
    public ItemTracker() {
        initComponents();
        
        setTransparentFrame(ItemTracker.this, panelBody);
        setTransparentFrame(btnFormLocation, btnFormScan);
        
        switchTrackerForm(ItemTrackerLocation);
    }
    
    public void switchTrackerForm(JComponent com) {
        setForm(panelBody, com);
        
        if (com == ItemTrackerLocation) {
            btnFormLocation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectINSY/resources/interface/btnTracker_active.png")));
            btnFormScan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectINSY/resources/interface/btnTracker.png")));
            
            ItemTrackerLocation.refreshTableInventory();
            ItemTrackerLocation.repopulateFilterComboBox();
        } else {
            btnFormLocation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectINSY/resources/interface/btnTracker.png")));
            btnFormScan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectINSY/resources/interface/btnTracker_active.png")));
            
            ItemTrackerScan.repopulateSuggestions();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        panelBody = new javax.swing.JPanel();
        panelPage = new javax.swing.JPanel();
        labelFormScan = new javax.swing.JLabel();
        btnFormScan = new javax.swing.JButton();
        labelFormLocation = new javax.swing.JLabel();
        btnFormLocation = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1840, 900));
        setMinimumSize(new java.awt.Dimension(1840, 900));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1840, 900));

        panelMain.setBackground(new java.awt.Color(255, 255, 255));
        panelMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(25, 102, 24), 2));

        panelBody.setBackground(new java.awt.Color(255, 255, 255));
        panelBody.setLayout(new java.awt.BorderLayout());

        panelPage.setBackground(new java.awt.Color(255, 255, 255));
        panelPage.setLayout(null);

        labelFormScan.setFont(new java.awt.Font("Bebas", 0, 24)); // NOI18N
        labelFormScan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFormScan.setText("SCAN ITEM");
        labelFormScan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelPage.add(labelFormScan);
        labelFormScan.setBounds(920, 6, 910, 30);

        btnFormScan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectINSY/resources/interface/btnTracker.png"))); // NOI18N
        btnFormScan.setBorder(null);
        btnFormScan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFormScan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormScanActionPerformed(evt);
            }
        });
        panelPage.add(btnFormScan);
        btnFormScan.setBounds(920, 0, 909, 40);

        labelFormLocation.setFont(new java.awt.Font("Bebas", 0, 24)); // NOI18N
        labelFormLocation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFormLocation.setText("ITEM LOCATION");
        labelFormLocation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelPage.add(labelFormLocation);
        labelFormLocation.setBounds(10, 6, 900, 30);

        btnFormLocation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectINSY/resources/interface/btnTracker.png"))); // NOI18N
        btnFormLocation.setToolTipText("");
        btnFormLocation.setBorder(null);
        btnFormLocation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFormLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormLocationActionPerformed(evt);
            }
        });
        panelPage.add(btnFormLocation);
        btnFormLocation.setBounds(0, 0, 920, 40);

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainLayout.createSequentialGroup()
                .addComponent(panelPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBody, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFormLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormLocationActionPerformed
        switchTrackerForm(ItemTrackerLocation);
    }//GEN-LAST:event_btnFormLocationActionPerformed

    private void btnFormScanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormScanActionPerformed
        switchTrackerForm(ItemTrackerScan);
    }//GEN-LAST:event_btnFormScanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFormLocation;
    private javax.swing.JButton btnFormScan;
    private javax.swing.JLabel labelFormLocation;
    private javax.swing.JLabel labelFormScan;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelPage;
    // End of variables declaration//GEN-END:variables
}
